//! Module handles parsing a bitmap font and placing a string
//! Only supports ASCII characters
//! Format is https://www.angelcode.com/products/bmfont/doc/file_format.html
//! Generated by https://snowb.org/

const std = @import("std");
const testing = std.testing;
const Allocator = std.mem.Allocator;

const Vec2 = @import("root.zig").Vec2;

pub const TypographyError = error{
    NoFontFileLineTag,
    FontFileLineTagNotRecognized,
    FontFilePropMissingKey,
    FontFilePropMissingValue,
    FontFileMultipleCharIdsInOneLine,
    FontFileCharMustHaveIdSetBeforeOtherProps,
    FontFilePaddingMissingComma,
};

pub const Glyph = struct {
    font_has_value: bool = false,

    x_atlas: f32 = 0,
    y_atlas: f32 = 0,
    width_atlas: f32 = 0,
    height_atlas: f32 = 0,
    x_offset: f32 = 0,
    y_offset: f32 = 0,
    x_advance: f32 = 0,

    pub fn tex_coord(self: *const Glyph) Vec2 {
        return Vec2.init(self.x_atlas, self.y_atlas);
    }

    pub fn tex_dimen(self: *const Glyph) Vec2 {
        return Vec2.init(self.width_atlas, self.height_atlas);
    }

    pub fn scaledDim(self: *const Glyph, scale: f32) Vec2 {
        return Vec2.init(self.width_atlas, self.height_atlas).multScalar(scale);
    }

    pub fn offset(self: *const Glyph, scale: f32) Vec2 {
        return Vec2.init(self.x_offset, -self.y_offset).multScalar(scale);
    }

    pub fn cursorAdvance(self: *const Glyph, scale: f32) f32 {
        return self.x_advance * scale;
    }
};

const FontFileTags = enum { info, common, page, chars, char, kerning };
const FontFileProps = enum { size, padding, line_height, base, scaleW, scaleH, id, x, y, width, height, xoffset, yoffset, xadvance };

pub const Font = struct {
    size: f32 = 0,
    padding: f32 = 0,
    scale_w: f32 = 0, // Atlas width
    scale_h: f32 = 0, // Atlas height
    line_height: f32 = 0, // y-distance between new lines
    base: f32 = 0,
    glyphs: [255]Glyph = @splat(.{}),

    pub fn init(io: std.Io, absolute_path: []const u8) !Font {
        const file = try std.Io.Dir.openFileAbsolute(io, absolute_path, .{});
        defer file.close(io);

        var file_buffer: [1024]u8 = undefined;
        var reader = file.reader(io, &file_buffer);

        var font: Font = .{};
        while (try reader.interface.takeDelimiter('\n')) |line| {
            var line_it = std.mem.tokenizeScalar(u8, line, ' ');
            const tag_string = line_it.next() orelse return TypographyError.NoFontFileLineTag;
            const tag = std.meta.stringToEnum(FontFileTags, tag_string) orelse return TypographyError.FontFileLineTagNotRecognized;

            var glyph_id: i32 = -1;
            while (line_it.next()) |prop| {
                var prop_it = std.mem.splitScalar(u8, prop, '=');
                const prop_type_string = prop_it.next() orelse return TypographyError.FontFilePropMissingKey;
                const prop_type = std.meta.stringToEnum(FontFileProps, prop_type_string) orelse continue;

                const value_string = prop_it.next() orelse return TypographyError.FontFilePropMissingValue;
                const value: i32 = switch (prop_type) {
                    .padding => blk: {
                        const comma_index = std.mem.find(u8, value_string, ",") orelse return TypographyError.FontFilePaddingMissingComma;
                        break :blk try std.fmt.parseInt(i32, value_string[0..comma_index], 10);
                    },
                    else => try std.fmt.parseInt(i32, value_string, 10),
                };

                switch (tag) {
                    .info => {
                        switch (prop_type) {
                            .size => font.size = @floatFromInt(value),
                            .padding => font.padding = @floatFromInt(value),
                            else => {},
                        }
                    },
                    .common => {
                        switch (prop_type) {
                            .line_height => font.line_height = @floatFromInt(value),
                            .base => font.base = @floatFromInt(value),
                            .scaleW => font.scale_w = @floatFromInt(value),
                            .scaleH => font.scale_h = @floatFromInt(value),
                            else => {},
                        }
                    },
                    .page => {},
                    .chars => {},
                    .char => {
                        if (glyph_id == -1 and prop_type != .id) return TypographyError.FontFileCharMustHaveIdSetBeforeOtherProps;

                        switch (prop_type) {
                            .id => {
                                if (glyph_id != -1) return TypographyError.FontFileMultipleCharIdsInOneLine;
                                glyph_id = value;
                                font.glyphs[@intCast(glyph_id)].font_has_value = true;
                            },
                            .x => font.glyphs[@intCast(glyph_id)].x_atlas = @floatFromInt(value),
                            .y => font.glyphs[@intCast(glyph_id)].y_atlas = @floatFromInt(value),
                            .width => font.glyphs[@intCast(glyph_id)].width_atlas = @floatFromInt(value),
                            .height => font.glyphs[@intCast(glyph_id)].height_atlas = @floatFromInt(value),
                            .xoffset => font.glyphs[@intCast(glyph_id)].x_offset = @floatFromInt(value),
                            .yoffset => font.glyphs[@intCast(glyph_id)].y_offset = @floatFromInt(value),
                            .xadvance => font.glyphs[@intCast(glyph_id)].x_advance = @floatFromInt(value),
                            else => {},
                        }
                    },
                    .kerning => {},
                }
            }
        }

        return font;
    }

    pub fn deinit(_: *@This()) void {} // No OP, but allows users to deinit and to not worry about future changes

    pub fn dimensions(self: *const Font) Vec2 {
        return Vec2.init(self.size, self.size);
    }

    pub fn getScale(self: *const Font, size: f32) f32 {
        return size / self.size;
    }

    pub fn scaledLineHeight(self: *const Font, scale: f32) f32 {
        return self.line_height * scale;
    }
};

test "Parse Test Font File" {
    const io: std.Io = std.testing.io;
    var cwd = std.Io.Dir.cwd();

    const test_file_name = "font_test.fnt";
    const file = try cwd.createFile(io, test_file_name, .{ .read = true });

    try file.writePositionalAll(io,
        \\info face="default" size=72 bold=0 italic=0 charset="32-59,61,63-91,93-95,97-125" unicode=1 stretchH=100 smooth=1 aa=1 padding=10,10,10,10 spacing=1,1 outline=0
        \\common lineHeight=72 base=55 scaleW=424 scaleH=426 pages=1 packed=0 alphaChnl=0 redChnl=4 greenChnl=4 blueChnl=4
        \\page id=0 file="default.png"
        \\chars count=90
        \\char id=32 x=0 y=0 width=0 height=0 xoffset=0 yoffset=0 xadvance=20 page=0 chnl=15
        \\char id=33 x=389 y=192 width=10 height=52 xoffset=5 yoffset=5 xadvance=20 page=0 chnl=15
        \\char id=34 x=297 y=406 width=22 height=18 xoffset=2 yoffset=5 xadvance=26 page=0 chnl=15
        \\char id=35 x=172 y=318 width=42 height=52 xoffset=-1 yoffset=5 xadvance=41 page=0 chnl=15
        \\char id=36 x=217 y=0 width=41 height=61 xoffset=-1 yoffset=1 xadvance=41 page=0 chnl=15
    , 0);
    file.close(io);
    defer {
        cwd.deleteFile(io, test_file_name) catch |err| {
            std.debug.print("Error deleting test file: {any}", .{err});
        };
    }

    const path = try cwd.realPathFileAlloc(io, "font_test.fnt", std.testing.allocator);
    defer std.testing.allocator.free(path);
    const font: Font = try .init(io, path);

    try std.testing.expect(font.size == 72);
    try std.testing.expect(font.padding == 10);
    try std.testing.expect(font.glyphs[34].x_offset == 2);
    try std.testing.expect(font.glyphs[34].y_offset == 5);
    try std.testing.expect(font.glyphs[34].x_advance == 26);
}
